### ISSUE TITLE
Inconsistent array names between properties files

### ISSUE THREAD

**Issue by MatthieuSchaller** [ICRAR/VELOCIraptor-STF#109] opened 2021-07-10 16:55 UTC
**Describe the bug**

When using the hdf5 output but *not* parallel-hdf5, some arrays have a different name in the `.0` file compared to all the others.

The three problematic fields are:
 - `SubgridMasses_average_bh` in the 0th file and `SubgridMasses_index_0_average_bh` in the others.
 -  `SubgridMasses_max_bh` in the 0th file and `SubgridMasses_index_0_max_bh` in the others.
 -  `SubgridMasses_min_bh` in the 0th file and `SubgridMasses_index_0_min_bh` in the others.

These are three of the four "extra BH properties" listed in our VR config file. The fourth quantity
is computed in apertures and somehow ends up with the same name in all the files.

extract of config:
```
# Collect the BH subgrid masses and compute the max, min, average and total mass in apertures                                                                                                                                                                                             
BH_internal_property_names=SubgridMasses,SubgridMasses,SubgridMasses,SubgridMasses,
BH_internal_property_input_output_unit_conversion_factors=1.0e10,1.0e10,1.0e10,1.0e10,
BH_internal_property_calculation_type=max,min,average,aperture_total,
BH_internal_property_output_units=solar_mass,solar_mass,solar_mass,solar_mass,
```

So, only extra properties computed at the level of the whole group seem affected. 

I don't know whether the same problem appears for gas or star extra properties since all the ones we use
are also computed in apertures, not over the whole group.

**To Reproduce**
1. Latest master
2. Compile with `VR_HDF5=ON VR_ALLOWPARALLELHDF5=OFF VR_OPENMP=OFF VR_MPI=ON VR_USE_HYDRO=ON` (the openMP bit is likely irrelevant)
3. Run over MPI on a swift-eagle snapshot
4. The distributed properties file use different names.

**Expected behavior**
The name should be the same in all files. The name in the `.0` file is the one that follows the other fields' convention.

**Log files**
Not relevant.

**Environment (please complete the following information):**
Not relevant

**Comment by MatthieuSchaller** [comment] 2021-07-10 16:59
There seems to be a piece of code that corrects the fields to strip the `index_0` in the case where the array is Nx1 (as it is here) and that is followed by a broadcast to all ranks. But somehow this group of names seems to be missed by the broadcast procedure, making only rank 0 use the correct name.
That's as much of this code section that I could understand.

**Comment by rtobar** [comment] 2021-07-21 03:01
@MatthieuSchaller Without looking into any details, and just based on the comments and description on this tickets, this reminds me of #102, which was finally caused by a missed broadcast, and was fixed via #110. Would you mind trying again?

**Comment by MatthieuSchaller** [comment] 2021-07-21 08:08
I'll give that a go, yes.

**Comment by rtobar** [comment] 2021-11-04 02:49
@MatthieuSchaller is this still a problem? It sounds like it might be fixed already, so hopefully we can close this one.

**Comment by MatthieuSchaller** [comment] 2021-11-04 11:00
Yes, that is indeed fixed. Sorry for the delayed reaction.

**Comment by rtobar** [comment] 2021-11-04 13:26
No problem, glad to know I can just close this one :)

**Closed by rtobar** 2021-11-04 13:26 UTC
Labels: bug
