### ISSUE TITLE
VR does not run in MPI+hydro mode

### ISSUE THREAD

**Issue by MatthieuSchaller** [ICRAR/VELOCIraptor-STF#54] opened 2020-12-10 14:20 UTC
**Describe the bug**

Running VR with MPI switched on, OMP switched off and hydro switched on breaks on EAGLE boxes.

**To Reproduce**
1) Compile the latest master (cb4336de8421b7bada3e158c44755c41e9fab78b) with `VR_USE_HYDRO=ON`, `VR_MPI=ON` and `VR_OPENMP=OFF`.
2) Run `mpirun -np 16 stf -C vrconfig_3dfof_subhalos_SO_hydro.cfg -i eagle_0036 -o halos_mpi_0036 -I 2`

This is a standard XL snapshot with our standard config file.
The code segfaults after printing
```
[0000] [ 346.430] [ info] search.cxx:352 Finished linking across MPI domains in 1.258 [min]
```
somewhere in a MPI call trying to clear a vector of size 10^16 (!!).

The input can be found here if necessary: `/snap7/scratch/dp004/jlvc76/SWIFT/EoS_tests/swiftsim/examples/EAGLE_ICs/EAGLE_25/eagle_0036.hdf5` and `/snap7/scratch/dp004/jlvc76/SWIFT/EoS_tests/swiftsim/examples/EAGLE_ICs/EAGLE_25/vrconfig_3dfof_subhalos_SO_hydro.cfg`.

The same setup works either:
 - On 1 MPI rank
 - Without VR_USE_HYDRO

Note that the snapshot is made of one single file if that is relevant.

**Comment by rtobar** [comment] 2020-12-11 02:22
@MatthieuSchaller thanks for the report. I don't think I'll be able to look into this until early next week though. In the meanwhile, could you please share the data, or push for my cosma application to proceed? I tried to reproduce locally with some of the inputs I had received in the past but they seem to lack the fields needed by the hydro-enabled code.

**Comment by MatthieuSchaller** [comment] 2020-12-15 22:37
If it helps, there is smaller test case here:
 - /snap7/scratch/dp004/jlvc76/SWIFT/EoS_tests/swiftsim/examples/EAGLE_low_z/EAGLE_6/eagle_0000.hdf5
 -  /snap7/scratch/dp004/jlvc76/SWIFT/EoS_tests/swiftsim/examples/EAGLE_low_z/EAGLE_6/vrconfig_3dfof_subhalos_SO_hydro.cfg
 
 This one crashes about 20s after start so might be easier.
 
Config is: `cmake ../ -DVR_USE_HYDRO=ON -DCMAKE_BUILD_TYPE=Debug`
Run command line is: `stf -C vrconfig_3dfof_subhalos_SO_hydro.cfg -i eagle_0000 -o halos_0000 -I 2`

- Problem happens with gcc or ICC,
- Running with `-DVR_OPENMP=OFF` also crashes in the same way,
- Running without `VR_MPI_REDUCE` crashes in a different way. There the crash happens when reading in stuff.

**Comment by rtobar** [comment] 2020-12-16 02:38
Thanks @MatthieuSchaller for the extra information. I managed to reproduce this locally with the data you pointed above, I hope I can post an update soon with some information

**Comment by rtobar** [comment] 2020-12-16 04:02
Running under valgrind revealed an invalid write:

```
==14074==    by 0x2D2CC6: MPISendReceiveFOFHydroInfoBetweenThreads(Options&, fofid_in*, std::vector<long long, std::allocator<long long> >&, std::vector<float, std::allocator<float> >&, int, int, ompi_communicator_t*&) (mpiroutines.cxx:2697)
```

The in gdb the reason became clear: the `proprecvbuff` vector needed to be properly sized before receiving data. Its size should be the same that `propsendbuff`, which in turn should be the size of `indicessend` times `numextrafields`.

On a new `issue-54` branch I fixed the resizing of `proprecvbuff` to accommodate for all incoming data, and also added an assertion to make sure the sizes of the input vectors are related to each other as expected. After these changes I can run the code to completion. @MatthieuSchaller please confirm that this is working for you too.

I also tried out running without `VR_MPI_REDUCE` and also got a crash. That looks like a separate issue though, so I'll create a separate ticket to keep track of it separately.

**Comment by MatthieuSchaller** [comment] 2020-12-16 08:50
I confirm this works both with and without OpenMP (as expected since unrelated). Thanks for tracking this down!

(I am never brave enough to fire up  valgrind inside an mpirun call...)

**Comment by rtobar** [comment] 2020-12-16 08:57
Great! I merged this into the `master` branch now, thanks for testing!

**Closed by rtobar** 2020-12-16 08:57 UTC
