### ISSUE TITLE
Compiling with DVR_USE_GAS=ON but no other options doesn't work

### ISSUE THREAD

**Issue by JBorrow** [ICRAR/VELOCIraptor-STF#91] opened 2021-06-18 09:02 UTC
**Describe the bug**
Compiling with `VR_USE_GAS=ON` (but not the rest of `VR_USE_HYDRO=ON`) doesn't work.

**To Reproduce**
`cmake ..  -DVR_USE_GAS=ON`
Latest master.
`make -j`

**Expected behavior**
The build works.

**Log files**
```In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/bgfield.cxx(7):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/haloproperties.cxx(9):
In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/fofalgo.cxx(5):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/mpihdfio.cxx(9):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/mpigadgetio.cxx(9):
In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/mpiramsesio.cxx(9):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.cxx(5):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/ramsesio.cxx(20):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/localbgcomp.cxx(7):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/exceptions.cxx(9):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/hdfio.cxx(26):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(7):
In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.cxx(5):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/mpiroutines.cxx(14):
In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/nchiladaio.cxx(7):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/mpinchiladaio.cxx(11):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/omproutines.cxx(11):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/unbind.cxx(8):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/mpitipsyio.cxx(10):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/swiftinterface.cxx(6):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/localfield.cxx(8):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/io.cxx(7):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/mpivar.cxx(9):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/gadgetio.cxx(7):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/tipsyio.cxx(7):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/buildandsortarrays.cxx(5):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/utilities.cxx(6):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/logging.h(7),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/ui.cxx(6):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

In file included from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/stf.h(8),
                 from /cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/search.cxx(9):
/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/allvars.h(2488): error: identifier "aperture_M_gas_highT" is undefined
  		aperture_M_gas_highT[i]*=opt.h;
  		^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3106): error: class "NBody::Particle" has no member "GetSFR"
  		   auto sfr = Pval->GetSFR();
  		                    ^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3119): error: class "NBody::Particle" has no member "GetZmet"
                         pdata[i].Z_mean_gas_highT_incl += massval * Pval->GetZmet();
                                                                           ^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3171): error: class "PropData" has no member "M_gas_nsf"
  	    pdata[hostindex].M_gas_nsf_incl += pdata[i].M_gas_nsf;
  	                                                ^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3172): error: class "PropData" has no member "M_gas_sf"
  	    pdata[hostindex].M_gas_sf_incl += pdata[i].M_gas_sf;
  	                                               ^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3189): error: class "PropData" has no member "M_gas_nsf"
              pdata[i].M_gas_nsf_incl += pdata[i].M_gas_nsf;
                                                  ^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3190): error: class "PropData" has no member "M_gas_sf"
              pdata[i].M_gas_sf_incl += pdata[i].M_gas_sf;
                                                 ^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3415): error: class "NBody::Particle" has no member "GetSFR"
                 sfr[j] = Part[taggedparts[j]].GetSFR();
                                               ^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3417): error: class "NBody::Particle" has no member "GetZmet"
                 Zgas[j] = Part[taggedparts[j]].GetZmet();
                                                ^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3483): error: class "NBody::Particle" has no member "GetSFR"
                              sfr[offset+j] = PartDataGet[taggedparts[j]].GetSFR();
                                                                          ^

/cosma/home/dc-borr1/c6dataspace/SPHENIX_Tests/swiftsim/curl_3d/examples/nIFTyCluster/Baryonic/VELOCIraptor-STF/src/substructureproperties.cxx(3485): error: class "NBody::Particle" has no member "GetZmet"
                              Zgas[offset+j] = PartDataGet[taggedparts[j]].GetZmet();
                                                                           ^```

**Comment by JBorrow** [comment] 2021-06-18 09:05
Note that you can't run on e.g. an adbaiatic run with DVR_USE_HYDRO=ON because it complains about missing sub-grid quantities like SFR.

**Comment by rtobar** [comment] 2021-06-18 11:41
This looks like a duplicate of #70, which I had half-forgotten about. I seem to remember there is a branch with some changes (maybe I haven't pushed it though), but in any case there was still some doubts I had that needed clarification with @cdplagos before fully fixing things.

I'm closing this as a duplicate anyway, I'll try to address #70 as a priority.

**Closed by rtobar** 2021-06-18 11:41 UTC

**Comment by rtobar** [comment] 2021-06-18 11:46
The branch with the (partial) fixes exists indeed (`issue-70`).

**Comment by JBorrow** [comment] 2021-06-18 12:20
Thanks, apologies for the dupe.

**Comment by rtobar** [comment] 2021-06-18 13:27
No problem ;-)
